server:
  port: ${SERVER_PORT:8084}
  servlet:
    context-path: /api/v1/psp-simulator

spring:
  application:
    name: psp-simulator-service
  thymeleaf:
    cache: false

app:
  callback:
    callback-secret: ${PSP_CALLBACK_SECRET:local-psp-callback-secret}
    connect-timeout: 2s
    read-timeout: 5s
  environment: ${APP_ENV:local}

logging:
  file:
    path: ${LOG_PATH:services/${spring.application.name}/logs}
