{
 "title": "Metrics Overview",
 "time": { "from": "now-1m", "to": "now" },
 "templating": {
  "list": [
   { "name": "service_name", "label": "Service name", "query": { "query": "label_values(service)" } },
   { "name": "env", "label": "Env", "query": { "query": "label_values(environment)" } }
  ]
 },
 "panels": [
  { "title": "HTTP metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "2xx Responses",
   "type": "stat",
   "description": "Total number of successful HTTP responses during the selected time range. Internal Prometheus scrape requests are excluded.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(http_server_requests_seconds_count{service=~\"$service_name\",status=~\"2..\",uri!=\"UNKNOWN\",uri!=\"/actuator/prometheus\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx Responses",
   "type": "stat",
   "description": "Total number of 4xx HTTP responses during the selected time range.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(http_server_requests_seconds_count{service=~\"$service_name\",status=~\"4..\",uri!=\"UNKNOWN\",uri!=\"/actuator/prometheus\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx Responses",
   "type": "stat",
   "description": "Total number of 5xx HTTP responses during the selected time range.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(http_server_requests_seconds_count{service=~\"$service_name\",status=~\"5..\",uri!=\"UNKNOWN\",uri!=\"/actuator/prometheus\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average 2xx RPS",
   "type": "stat",
   "description": "Average number of successful 2xx HTTP responses per second during the selected time range.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{service=~\"$service_name\",status=~\"2..\",uri!=\"UNKNOWN\",uri!=\"/actuator/prometheus\"}[$__range]))\r\n/\r\n$__range_s",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average 4xx RPS",
   "type": "stat",
   "description": "Average number of 4xx HTTP responses per second during the selected time range.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{service=~\"$service_name\",status=~\"4..\",uri!=\"UNKNOWN\",uri!=\"/actuator/prometheus\"}[$__range]))\r\n/\r\n$__range_s",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average 5xx RPS",
   "type": "stat",
   "description": "Average number of 5xx HTTP responses per second during the selected time range.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{service=~\"$service_name\",status=~\"5..\",uri!=\"UNKNOWN\",uri!=\"/actuator/prometheus\"}[$__range]))\r\n/\r\n$__range_s",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Latency by Endpoint",
   "type": "timeseries",
   "description": "Average HTTP request processing time grouped by endpoint and method for the selected service. Internal Prometheus scrape requests are excluded.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(uri, method) (rate(http_server_requests_seconds_sum{service=~\"$service_name\", uri!=\"UNKNOWN\", uri!=\"/actuator/prometheus\", uri!=\"/**\"}[$__rate_interval])) / (sum by(uri, method) (rate(http_server_requests_seconds_count{service=~\"$service_name\", uri!=\"UNKNOWN\", uri!=\"/actuator/prometheus\", uri!=\"/**\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}