spring:
  application:
    name: order-service
  datasource:
    url: ${ORDER_DATASOURCE_URL:jdbc:postgresql://localhost:5433/order_db}
    username: ${ORDER_DATASOURCE_USERNAME:admin}
    password: ${ORDER_DATASOURCE_PASSWORD:pwd}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  grpc:
    client:
      channels:
        catalog-service:
          address: ${CATALOG_GRPC_ADDRESS:static://localhost:9091}

server:
  port: ${SERVER_PORT:8082}

app:
  environment: ${APP_ENV:local}

logging:
  file:
    path: ${LOG_PATH:services/${spring.application.name}/logs}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true

  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
    tags:
      application: ${spring.application.name}
      environment: ${app.environment}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
