global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: api-gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - __API_GATEWAY_METRICS_TARGET__
        labels:
          service: api-gateway
          environment: __APP_ENV__

  - job_name: catalog-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - __CATALOG_SERVICE_METRICS_TARGET__
        labels:
          service: catalog-service
          environment: __APP_ENV__

  - job_name: order-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - __ORDER_SERVICE_METRICS_TARGET__
        labels:
          service: order-service
          environment: __APP_ENV__
