spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: catalog-service
              uri: ${CATALOG_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/v1/catalog/**
              filters:
                - PreserveHostHeader
                - DedupeResponseHeader=X-Correlation-Id RETAIN_LAST
            - id: order-service
              uri: ${ORDER_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/v1/orders/**
              filters:
                - PreserveHostHeader
                - DedupeResponseHeader=X-Correlation-Id RETAIN_LAST

server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework

app:
  environment: ${APP_ENV:local}

logging:
  file:
    path: ${LOG_PATH:logs}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics,prometheus

  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${app.environment}

  endpoint:
    health:
      probes:
        enabled: true
    gateway:
      access: read_only
